const express = require('express')
const router = express.Router()
const nodemailer = require('nodemailer')
const { config } = require('../../middlewares/config.js')
const Members = require('../../controllers/membersCtrl')
const Groups = require('../../controllers/groupsCtrl')
const Projects = require('../../controllers/projectsCtrl')
const Tickets = require('../../controllers/ticketsCtrl')
const Comments = require('../../controllers/commentsCtrl')
const UserData = require('../../controllers/userDataCtrl')
const Statuts = require('../../controllers/statutsCtrl')
const Urgence = require('../../controllers/urgenceCtrl')
const Categories = require('../../controllers/categoriesCtrl')
const Tools = require('../../controllers/toolsCtrl')

router.get('/user_data', UserData.getAll)

router.get("/members", Members.getAll)
router.get("/member/:id", Members.getByIdMember)
router.get("/members/project/:idProject", Members.getByIdProject)
router.get("/members/group/:idGroup", Members.getByIdGroup)
router.get("/member/:idMember/project/:idProject", Members.getByIdMemberIdProject)
router.put("/membersProject", Members.updateByIdMemberProject)
router.post("/membersProject", Members.insertByIdMemberProject)
router.delete("/membersProject", Members.removeByIdMemberProject)
router.post("/email", Members.sendMail)
router.get("/groups", Groups.getAll)
router.get("/group/:idGroup", Groups.getByIdGroup)
router.get("/projects", Projects.getAll)
router.get("/project/:idProject", Projects.getByIdProject)
router.get("/projects/group/:idGroup", Projects.getByIdGroup)
router.get("/projects/member/:idMember", Projects.getByIdMember)
router.get("/projects/statut/:idStatut", Projects.getByIdStatut)
router.get("/projects/type/:type", Projects.getByType)
router.get("/projectRelation", Projects.getByLink)
router.put("/project", Projects.updateById)
router.post("/project", Projects.createProject)
router.post("/projectRelation", Projects.createProjectRelation)
router.delete("/projectRelation", Projects.deleteProjectRelation)
router.delete("/project/:idProject", Projects.deleteByIdProject)
router.get("/tickets", Tickets.getAll)
router.get("/ticket/:idTicket", Tickets.getByIdTicket)
router.get("/tickets/member/:idMember", Tickets.getByIdMember)
router.get("/tickets/project/:idProject", Tickets.getByIdProject)
router.get("/tickets/statut/:idStatut", Tickets.getByIdStatut)
router.get("/tickets/statut/:idStatut/project/:idProject", Tickets.getByIdStatutIdProject)
router.post("/tickets", Tickets.insertTicket)
//router.post("/ticketMembers", Tickets.insertTicketMembersAffected)
router.delete("/ticket/:idTicket", Tickets.removeTicket)
router.put("/tickets", Tickets.updateTicketById)
router.get("/comments", Comments.getAll)
router.get("/comment/:idComment", Comments.getByIdComment)
router.get("/comments/member/:idMember", Comments.getByIdMember)
router.get("/comments/ticket/:idTicket", Comments.getByIdTicket)
router.get("/comments/tool/:idTool", Comments.getByIdTool)
router.post("/comments", Comments.insertComment)
router.post("/commentsTool", Comments.insertCommentTool)
router.get("/statuts", Statuts.getAll)
router.get("/urgence", Urgence.getAll)
router.get("/categories", Categories.getAll)
router.get("/category/:idCategory", Categories.getById)
router.post("/category", Categories.insertById)
router.get("/tools", Tools.getAll)
router.get("/tool/:idTool", Tools.getByIdTool)
router.get("/tools/category/:idCategory", Tools.getByIdCategory)
router.post("/tool", Tools.insertById)
router.delete("/tool/:idTool", Tools.deleteById)

module.exports = router